{
    "name": "projects",
    "application": True,
    "summary": "This Application for Projects .",
    "version": "1.0.0",
    "category": "",
    "website": "www.asjhaskjd/saasg/sjdhj",
    "author": "Chirag Vaghasiya",
    "license": "",
    "installable": True,
    "depends": ['project'],
    "development_status": "",
    "maintainers": [],
    'demo':[],
    "excludes": [],
    "data": [
        'security/ir.model.access.csv',
        'data/projectt_tags_data.xml',
        'views/projectt_tags.xml',
        'views/project_task.xml',
    ],
    "sequence": -500,
    'license': 'LGPL-3',
}